### ISSUE TITLE
Dropped 3 spans due to ConnectException(Connection refused)

### ISSUE THREAD

**Issue by YangTingWei** [zpng/spring-cloud-microservice-examples#2]
请问启动zipkin服务时出现这种错误是什么原因呢？
本地amqb-server开启了，但是一直提示ACCESS_REFUSED，该如何解决呢？
谢谢

**Comment by zpng** [comment]
This is a bug, thank you, I will try to fix it!

**Comment by zpng** [comment]
I have fix this bug, just pull the newest version. It's because
    if ("$BOM_VERSION".toString() == "Brixton.RELEASE") {
        runtime "io.zipkin:zipkin-ui:1.40.2"
    } else {
        runtime "io.zipkin.java:zipkin-autoconfigure-ui:1.14.1"
    }
wrong zipkin-ui version
